export const languages = [
  { id: 'af', name: 'Afrikaans' },
  { id: 'sq', name: 'Albanian' },
  { id: 'ar', name: 'Arabic' },
  { id: 'eu', name: 'Basque' },
  { id: 'bn', name: 'Bengali' },
  { id: 'bg', name: 'Bulgarian' },
  { id: 'ca', name: 'Catalan' },
  { id: 'zh_CN', name: 'Chinese, simplified' },
  { id: 'zh_TW', name: 'Chinese, traditional' },
  { id: 'hr', name: 'Croatian' },
  { id: 'cs', name: 'Czech' },
  { id: 'da', name: 'Danish' },
  { id: 'nl', name: 'Dutch' },
  { id: 'en', name: 'English' },
  { id: 'eo', name: 'Esperanto' },
  { id: 'et', name: 'Estonian' },
  { id: 'fo', name: 'Faroese' },
  { id: 'fa', name: 'Farsi/Persian' },
  { id: 'fi', name: 'Finnish' },
  { id: 'fr', name: 'French' },
  { id: 'de', name: 'German' },
  { id: 'el', name: 'Greek' },
  { id: 'he', name: 'Hebrew' },
  { id: 'hi', name: 'Hindi' },
  { id: 'hu', name: 'Hungarian' },
  { id: 'is', name: 'Icelandic' },
  { id: 'id', name: 'Indonesian' },
  { id: 'it', name: 'Italian' },
  { id: 'ja', name: 'Japanese' },
  { id: 'kn', name: 'Kannada' },
  { id: 'km', name: 'Khmer' },
  { id: 'ko', name: 'Korean' },
  { id: 'ku', name: 'Kurdish' },
  { id: 'lo', name: 'Lao' },
  { id: 'lv', name: 'Latvian' },
  { id: 'lt', name: 'Lithuanian' },
  { id: 'mk', name: 'Macedonian' },
  { id: 'ms', name: 'Malay' },
  { id: 'mr', name: 'Marathi' },
  { id: 'no', name: 'Norwegian' },
  { id: 'pl', name: 'Polish' },
  { id: 'pt', name: 'Portuguese' },
  { id: 'ro', name: 'Romanian' },
  { id: 'ru', name: 'Russian' },
  { id: 'sr', name: 'Serbian' },
  { id: 'sk', name: 'Slovak' },
  { id: 'sl', name: 'Slovenian' },
  { id: 'es', name: 'Spanish' },
  { id: 'sw', name: 'Swahili' },
  { id: 'sv', name: 'Swedish' },
  { id: 'ta', name: 'Tamil' },
  { id: 'te', name: 'Telugu' },
  { id: 'th', name: 'Thai' },
  { id: 'tr', name: 'Turkish' },
  { id: 'uk', name: 'Ukrainian' },
  { id: 'ur', name: 'Urdu' },
  { id: 'vi', name: 'Vietnamese' },
  { id: 'cy', name: 'Welsh' },
];

export const units = [
  { id: 'y', name: 'Year' },
  { id: 'mo', name: 'Month' },
  { id: 'w', name: 'Week' },
  { id: 'd', name: 'Day' },
  { id: 'h', name: 'Hour' },
  { id: 'm', name: 'Minute' },
  { id: 's', name: 'Second' },
  { id: 'ms', name: 'Millisecond' },
];
