name: Build And Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1.1.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test & Build
        run: |
          npm ci
          npm run test:prod
          npm run build:prod
          npm run pack

      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package-version.outputs.current-version}}
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: dist/**.tgz

      - name: Publish to npm
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
        run: npm publish dist/ngx-humanize-duration
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
